blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/guivin/dht-prometheus-exporter/discussions
    about: Ask questions and discuss with the community
